[features]
resolution = true
skip-lint = false

[programs.localnet]
solmobile_compute = "SoMC111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["programs/*"]

[[test.genesis]]
address = "SoMC111111111111111111111111111111111111111"
program = "programs/solmobile-compute/target/deploy/solmobile_compute.so" 